### ISSUE TITLE
Better error than "thread 'main' panicked at 'assertion failed: command.is_absolute()', src/formatter.rs:165:9"

### ISSUE THREAD

**Issue by justinwoo** [numtide/treefmt#179]
**Is your feature request related to a problem? Please describe.**

treefmt 0.4.1

I am getting `thread 'main' panicked at 'assertion failed: command.is_absolute()', src/formatter.rs:165:9` when treefmt cannot resolve a formatter's filepath (or something).

**Describe the solution you'd like**

I would like to get a written error message with

* What was attempted
* What was expected
* What is a possible resolution

**Describe alternatives you've considered**

Keeping this message the same and requiring everyone to look at the source code to have some clues as to what is going on

**Additional context**

I assume treefmt is meant to be used by people rather than some scripts

**Comment by zimbatm** [comment]
Can you share your `treefmt.toml` and on which OS you're running? If it's reaching the assertions, it's hitting a bug somewhere that I need to reproduce.

**Comment by zimbatm** [comment]
And also the output of `treefmt -vvv`, or at least the last line that shows "Found {} at {}"

**Comment by justinwoo** [comment]
i'm using mac os 12.6 with an M2 with `command = "prettier"`

**Comment by zimbatm** [comment]
Can you give me the output of `treefmt -vvv 2>&1 | grep " Found "` ?

**Comment by brianmcgee** [comment]
This has all changed in v2.
